name:         WWW-Alexa-TrafficRank
version:      1.6
version_from: lib/WWW/Alexa/TrafficRank.pm
installdirs:  site
requires:     LWP::UserAgent:                0
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
